# Generated by Django 3.2 on 2021-05-03 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bovino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bovine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('date_birth', models.DateField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='bovinos/')),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_of', to='bovino.brand')),
            ],
            options={
                'verbose_name': 'Bovine',
                'verbose_name_plural': 'Bovines',
            },
        ),
    ]
