# Generated by Django 3.2.1 on 2021-05-08 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bovino', '0002_bovine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bovine',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bovino.brand'),
        ),
    ]
